### ISSUE TITLE
Improve documentation images

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_viberbot#2]
Some images in the documentation seem to be squeezed. Also there are images with windows screens. I think Windows is not relevant and does not to be featured. Please only provide screenshots of the browser window and use Linux for larger screenshots.

**Comment by anu0012** [comment]
Hey @mariobehling after removing height and width attributes from img tag, the images are no more squeezed.

**Comment by Manveer695** [comment]
@anu0012 Thanks for pointing it out, but after removing height and width attributes the images seem quite large. Is it ok? @mariobehling sir.
